project_name: pttd

builds:
  - binary: pttd
    main: .
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - none

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: atmelmicro
    name: pttd


brews:
  - name: pttd

    repository:
      owner: atmelmicro
      name: homebrew-pttd
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    homepage: "https://github.com/atmelmicro/pttd"
    description: "A push to talk daemon that allows global push to talk on Linux."
    license: MIT

    directory: Formula

    install: |
      bin.install "pttd"

    service: |
      run: [opt_bin/"pttd"]
      working_dir: var/"pttd"
      log_path: var/"log/pttd.log"
      error_log_path: var/"log/pttd-error.log"
      keep_alive: true

    skip_upload: auto  # don't publish pre-release tags

    commit_msg_template: "formula: update pttd to {{ .Tag }}"